apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBM0cyMk9GTVNXSVJYVFg1NAphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBkdVVtakI4TXNnZjNWbDF0d21tdUgxbTFyd1MvemRHT3JtSUNkV1BJCg==