apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: akev15/udagram-api-user:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
          volumeMounts:
            - mountPath: " ~/.aws"
              name: aws-secret
      volumes:
        - name: aws-secret
          configMap:
            name: aws-secret
